# Site
name: "Stouter's Blog"
title: "Stouter's Blog"
description: "과정을 담는 개발 블로그입니다."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
url: "https://comeintostout.github.io"
google_analytics: 'G-D9WLWPWS5Y'
#disqus: 'demowebsite'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
timezone: Asia/Seoul

# Authors
authors:
  stouter:
    name: 강성준
    display_name: Stouter
    avatar: 'assets/images/stouter.JPG'
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: rkdtjdwns916@gmail.com
    web: https://github.com/comeintostout
    linkedin: https://www.linkedin.com/in/%EC%84%B1%EC%A4%80-%EA%B0%95-8a8b6425a/
    description: "백엔드 개발자입니다."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-toc
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 9
paginate_path: /page:num/
    
# Other
toc:
  min_level: 1
  max_level: 3
  ordered_list: false
  no_toc_section_class: no_toc_section
  list_id: toc
  list_class: section-nav
  sublist_class: ''
  item_class: toc-entry
  item_prefix: toc-


markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
